In [ ]:
Sisè de primaria

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy.optimize import curve_fitgit 

In [38]:
import pandas as pd
from sodapy import Socrata

# Replace None with your app token "AVDM_Competencies" for authenticated access
client = Socrata("analisi.transparenciacatalunya.cat", "m9Y54hwBbAj3B7xBgcCqQEXBa")

# Fetch the first 2000 results as JSON and convert them to a Python list of dictionaries
results = client.get("rk5x-gny6",limit=1000000)

# Convert to pandas DataFrame
sise = pd.DataFrame.from_records(results)

# Display the DataFrame
print(sise)

         any codi_alumne   pcat pcat_cl pcat_ee  pcast pcast_cl pcast_ee  \
0       2023  3293538667   82.7   88.64   66.67     92      100    88.89   
1       2023  3293527446   73.7   81.82   55.56     81    86.36    72.22   
2       2023  3293515234     82   79.55   77.78   88.7    90.91    83.33   
3       2023  3293504013   53.5   68.18   22.22   71.8       75    66.67   
4       2023  3293493679   37.9   31.82   38.89    NaN      NaN      NaN   
...      ...         ...    ...     ...     ...    ...      ...      ...   
963028  2009         NaN  45.78   56.82   33.33  51.22    74.42    25.64   
963029  2009         NaN   74.7   81.82   66.67  95.12      100    89.74   
963030  2009         NaN  84.34     100   66.67  95.12     90.7      100   
963031  2009         NaN  61.45   84.09    35.9  69.51    93.02    43.59   
963032  2009         NaN  39.76   59.09   17.95  30.49    46.51    12.82   

         pmat pmat_nc  ... genere mes_naixement any_naixement  \
0        67.4   85.71 

In [39]:
# Select specific columns
sise = sise[['any','codi_alumne','pcat', 'pcast', 'pang', 'pmat', 'pmed']]

print(sise)

         any codi_alumne   pcat  pcast   pang   pmat   pmed
0       2023  3293538667   82.7     92    100   67.4  61.39
1       2023  3293527446   73.7     81  95.17   89.4  88.33
2       2023  3293515234     82   88.7   93.5    100  96.67
3       2023  3293504013   53.5   71.8  86.83   87.2  70.28
4       2023  3293493679   37.9    NaN    NaN    NaN  27.78
...      ...         ...    ...    ...    ...    ...    ...
963028  2009         NaN  45.78  51.22    NaN  57.83    NaN
963029  2009         NaN   74.7  95.12    NaN  84.34    NaN
963030  2009         NaN  84.34  95.12    NaN  89.16    NaN
963031  2009         NaN  61.45  69.51    NaN  79.52    NaN
963032  2009         NaN  39.76  30.49    NaN  77.11    NaN

[963033 rows x 7 columns]


In [40]:
# Count how many times each object appears in the column
value_counts = sise['any'].value_counts()

# To count the number of occurrences of a specific object (e.g., 'apple')
count23 = value_counts.get('2023', 0)  # Defaults to 0 if 'apple' isn't in the column
count22 = value_counts.get('2022', 0)  # Defaults to 0 if 'apple' isn't in the column
count21 = value_counts.get('2021', 0)  # Defaults to 0 if 'apple' isn't in the column
count20 = value_counts.get('2020', 0)  # Defaults to 0 if 'apple' isn't in the column
count19 = value_counts.get('2019', 0)  # Defaults to 0 if 'apple' isn't in the column
count18 = value_counts.get('2018', 0)  # Defaults to 0 if 'apple' isn't in the column
count17 = value_counts.get('2017', 0)  # Defaults to 0 if 'apple' isn't in the column
count16 = value_counts.get('2016', 0)  # Defaults to 0 if 'apple' isn't in the column
count15 = value_counts.get('2015', 0)  # Defaults to 0 if 'apple' isn't in the column
count14 = value_counts.get('2014', 0)  # Defaults to 0 if 'apple' isn't in the column
count13 = value_counts.get('2013', 0)  # Defaults to 0 if 'apple' isn't in the column

count6=np.array([count19,count18,count17,count16,count15,count14,count13])

print(count6)

[74792 74207 72036 71244 69526 66908 65598]


In [91]:
# mitjanes de les assignatures seleccionades per cada any començant pel 2009
msise=np.zeros([10,5])

for i in range(2010,2020):
    #selecciono l'any d'estudi
    an = sise[sise['any'] == str(i)]

    #per les diferents proves cal passar els valors que es troben en string a numeric
    pcat=pd.to_numeric(an['pcat'], errors='coerce')
    pcast=pd.to_numeric(an['pcast'], errors='coerce')
    pang=pd.to_numeric(an['pang'], errors='coerce')
    pmat=pd.to_numeric(an['pmat'], errors='coerce')
    pmed=pd.to_numeric(an['pmed'], errors='coerce')

    #elimina els NaN
    an = an.dropna()

    #mitjana de cada assigantura
    mcat=pcat.mean()
    mcast=pcast.mean()
    mang=pang.mean()
    mmat=pmat.mean()
    mmed=pang.mean()

    #array de mitjanes
    mi=np.array([mcat,mcast,mang,mmat,mmed])
    n=int(i-2010)
    msise[n]=mi

#print(any19.iloc[4])


print(msise)

[[73.65127923 71.18704022 71.37677347 78.23027282 71.37677347]
 [77.19818012 73.58237366 80.587098   80.89832119 80.587098  ]
 [79.66834068 76.62047947 74.30327956 80.27099827 74.30327956]
 [71.09451103 73.02916718 72.9923096  76.26586191 72.9923096 ]
 [75.55872021 75.41799631 75.18870689 81.04462962 75.18870689]
 [74.47592463 75.5943331  74.42300664 80.00011335 74.42300664]
 [74.54511527 74.05539365 73.93830321 77.87057138 73.93830321]
 [75.86877702 74.29946717 79.97269521 77.62723249 79.97269521]
 [73.56137572 76.99460305 76.27108357 79.23408807 76.27108357]
 [75.45656315 74.43666766 78.19418454 78.18107419 78.19418454]]


Quart de la ESO

In [86]:
import pandas as pd
from sodapy import Socrata

# Replace None with your app token "AVDM_Competencies" for authenticated access
client = Socrata("analisi.transparenciacatalunya.cat", "m9Y54hwBbAj3B7xBgcCqQEXBa")

# Fetch the first 2000 results as JSON and convert them to a Python list of dictionaries
results = client.get("59vm-wwq7",limit=1000000)

# Convert to pandas DataFrame
quart = pd.DataFrame.from_records(results)

# Display the DataFrame
print(quart)

         any codi_alumne   pcat pcat_cl pcat_ee  pcast pcast_cl pcast_ee  \
0       2023  3901524245  75.23   73.75   78.13   79.4       74     87.5   
1       2023  3903493698  65.61   70.11   59.38  74.55       68    84.38   
2       2023  4328915551  38.11   53.71   15.63   50.7       72    18.75   
3       2023  3901434261  89.37   90.15    87.5  86.45       92    78.13   
4       2023  3900118187  65.56   71.93   56.25  63.35       66    59.38   
...      ...         ...    ...     ...     ...    ...      ...      ...   
778548  2012         NaN   58.2      68    48.4  63.21    57.67    68.75   
778549  2012         NaN   76.3      80    72.6  60.65    80.67    40.63   
778550  2012         NaN  74.74      92   57.48  69.04    69.33    68.75   
778551  2012         NaN  69.23      84   54.45  77.83    80.67       75   
778552  2012         NaN  63.76      64   63.53  74.08    73.17       75   

         pang pang_co  ...            h_bitat pfran pfran_co pfran_cl  \
0        78.4 

In [89]:
# Select specific columns
quart = quart[['any','codi_alumne','pcat', 'pcast', 'pang', 'pmat', 'pcien']]

print(quart)

         any codi_alumne   pcat  pcast   pang   pmat  pcien
0       2023  3901524245  75.23   79.4   78.4  80.81   82.7
1       2023  3903493698  65.61  74.55     74  66.06  77.27
2       2023  4328915551  38.11   50.7     56  31.69  50.51
3       2023  3901434261  89.37  86.45   88.8  90.56  84.34
4       2023  3900118187  65.56  63.35   66.6  42.36  62.75
...      ...         ...    ...    ...    ...    ...    ...
778548  2012         NaN   58.2  63.21  50.78   74.8    NaN
778549  2012         NaN   76.3  60.65     44   83.8    NaN
778550  2012         NaN  74.74  69.04  61.33   64.9    NaN
778551  2012         NaN  69.23  77.83  85.11   89.5    NaN
778552  2012         NaN  63.76  74.08  49.89   75.6    NaN

[778553 rows x 7 columns]


In [96]:
# mitjanes de les assignatures seleccionades per cada any començant pel 2009
mquart=np.zeros([10,5])

for i in range(2014,2024):
    #selecciono l'any d'estudi
    an = quart[quart['any'] == str(i)]

    #per les diferents proves cal passar els valors que es troben en string a numeric
    pcat=pd.to_numeric(an['pcat'], errors='coerce')
    pcast=pd.to_numeric(an['pcast'], errors='coerce')
    pang=pd.to_numeric(an['pang'], errors='coerce')
    pmat=pd.to_numeric(an['pmat'], errors='coerce')
    pmed=pd.to_numeric(an['pcien'], errors='coerce')

    #elimina els NaN
    an = an.dropna()

    #mitjana de cada assigantura
    mcat=pcat.mean()
    mcast=pcast.mean()
    mang=pang.mean()
    mmat=pmat.mean()
    mmed=pang.mean()

    #array de mitjanes
    mi=np.array([mcat,mcast,mang,mmat,mmed])
    n=int(i-2014)
    mquart[n]=mi

#print(any19.iloc[4])


print(mquart)

[[77.13919146 76.39128032 66.85929037 69.10077    66.85929037]
 [71.78126747 75.14630959 69.28335208 68.66400243 69.28335208]
 [76.91410726 76.54853103 68.21337541 54.73101318 68.21337541]
 [74.56677417 77.24299503 74.14934108 70.15525603 74.14934108]
 [76.8166494  77.23828322 73.8890618  68.45209035 73.8890618 ]
 [77.5350502  78.5818933  74.08777653 68.75583594 74.08777653]
 [74.05019043 77.87794556 74.6744422  70.16924359 74.6744422 ]
 [76.48963662 78.06273372 70.48566276 66.67570017 70.48566276]
 [74.13762335 75.22558857 68.37993561 61.14603951 68.37993561]
 [72.31970247 71.65463187 73.88121071 62.30969979 73.88121071]]
